#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh 
Ugap = -40px
Dgap = -60px 
Lgap = -30px
Rgap = -30px

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          20
bspc config top_padding 	40px 
bspc config bottom_padding	60px
bspc config left_padding 	30px 
bspc config right_padding 	30px
#bspc config window {left Lgap, right Rgap, up Ugap, down Dgap}


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

